name: Publish Node.js package

on:
  release:
    types: [released, prereleased]

jobs:
  publish-npm:
    uses: ryze-digital/reusable-workflows/.github/workflows/publish-npm.yml@main
    secrets:
      npm_token: ${{secrets.npm_token}}